#image: adoptopenjdk/openjdk11:alpine-slim
image: docker:git

services:
    - docker:dind

variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375

stages:
    #    - build
    - test
    - deploy

before_script:
    #  - echo `pwd` # debug
    - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
    - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

#build:
#    stage: build
#    script:
#        - ./gradlew build
#    only:
#        - master

test:
    image: adoptopenjdk/openjdk11:alpine-slim
    stage: test
    script:
        - ./gradlew check
    only:
        - feature/*

deploy:
    image: adoptopenjdk/openjdk11:alpine-slim
    stage: deploy
    script:
        - ./gradlew deploy
    only:
        - dev
        - master

after_script:
    - echo "End CI"
