openapi: 3.0.3
info:
    title: Транспортные модели для Чайника
    description: 'Транспортные модели для связи различных компонентов IoT-прототипа Чайника'
    contact:
        email: okatov@datana.ru
    license:
        name: Proprietar
    version: 0.0.1
#externalDocs:
#  description: Find out more about Swagger
#  url: http://swagger.io
#servers:
#- url: http://localhost
tags:
    - name: processing-interpretation
      description: Коммуникация между процессингом данных и ML-интерпретатором
    - name: interpretation-ui
      description: Коммуникация между ML-интерпретатором данных и интерфейсом пользователя
    - name: processing-ui
      description: Коммуникация между процессингом и интерфейсом пользователя

paths:
    /tmp:
        get:
            responses:
                200:
                    description: tmp
                    content: {}

components:

    schemas:

        TemperaturesBundle:
            type: object
            properties:
                periodAveraging:
                    type: integer
                    format: int64
                data:
                    type: array
                    items:
                        $ref: '#/components/schemas/TemperatureItem'

        TemperatureItem:
            type: object
            properties:
                timestamp:
                    description: Количество миллисекунд от начала Unix-эпохи в UTC
                    type: integer
                    format: int64
                temperature:
                    description: Температура в цельсиях
                    type: number

