openapi: 3.0.3
info:
  title: Модели для передачи Видео-адаптер-Матмодель кислородного конвертера
  description: 'Транспортные модели для передачи данных от Видео-адаптера до Матмодели кислородного конвертера'
  contact:
    email: okatov@datana.ru
  license:
    name: Proprietar
  version: 0.0.1
externalDocs:
  description: Дополнительная информация
  url: https://conf.dds.lanit.ru/pages/viewpage.action?pageId=48956438
#servers:
#- url: http://localhost

paths:
  /tmp:
    get:
      responses:
        200:
          description: tmp
          content: {}

components:

  schemas:

    ConverterTransportMlUi:
      description: Транспортная модель для передачи данных от матмодели до UI кислородного конвертера
      allOf:
        - $ref: './spec-converter-ViMl.yaml#/components/schemas/ConverterTransportViMl'
        - type: object
          properties:
            angle:
              title: Угол конвертера
              description: Угол в градусах, на который наклонен конвертер, определенный средствами матмодели из кадра
              type: number
              format: double
            steelRate:
              title: Содержание стали
              description: Доля стали (от единицы) на поверхности при сливе плавки из конвертера
              type: number
              format: double
            slagRate:
              title: Содержание шлака
              description: Доля шлака (от единицы) на поверхности при сливе плавки из конвертера
              type: number
              format: double
