openapi: 3.0.3
info:
  title: Форматы моделей для кислородного конвертера
  description: 'Транспортные модели для связи различных компонентов кислородного конвертера'
  contact:
    email: okatov@datana.ru
  license:
    name: Proprietar
  version: 0.0.1
externalDocs:
  description: Дополнительная информация
  url: https://conf.dds.lanit.ru/pages/viewpage.action?pageId=48956438
#servers:
#- url: http://localhost

paths:
  /tmp:
    get:
      responses:
        200:
          description: tmp
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConverterMeltInfo'

components:

  schemas:

    ConverterMeltInfo:
      description: Мета-информация о плавке
      type: object
      properties:
        id:
          title: Идентификатор
          description: Уникальный идентификатор плавки. Строится из даты и номера плавки
          type: string
        timeStart:
          title: Время начала
          description: Время начала плавки в миллисекундах от Unix-эпохи в GMT
          type: integer
          format: int64
        meltNumber:
          title: № плавки
          type: string
          description: Номер плавки. Не уникален
        steelGrade:
          title: марка стали
          description: Марка выплавляемой стали
          type: string
        crewNumber:
          title: № бригады
          type: string
          description: Номер бригады, выполняющей плавку
        shiftNumber:
          title: № смены
          type: string
          description: Номер смены, в которую выполняется плавка
        mode:
          title: Режим прогона
          type: string
          description: "Режим, в котором прогоняется текущая плавка: боевая, эмуляция, тестовая"
          enum:
            - prod
            - emulation
            - test
        devices:
          $ref: '#/components/schemas/ConverterMeltDevices'

    ConverterMeltDevices:
      title: Оборудование
      description: Данные об оборудовании, которое используется для мониторинга на данном агрегате
      type: object
      properties:
        converter:
          $ref: '#/components/schemas/ConverterDevice'
        irCamera:
          $ref: '#/components/schemas/ConverterDevice'
        selsyn:
          $ref: '#/components/schemas/ConverterDevice'

    ConverterDevice:
      title: Прибор
      description: Прибор - источник данных о процессах и параметрах конвертера
      type: object
      properties:
        id:
          title: Идентификтор прибора
          description: Уникальный идентификатор прибора, с которого производится съем данных
          example: converter123-irCamera1
          type: string
        name:
          title: Название
          description: Название прибора
          example: "Камера на Конвертере-2"
          type: string
        uri:
          title: Адрес устройства
          description: Адрес файла или устройства, с которого снимать изображение
          type: string
          example: "case-case1/video.ravi"
        type:
          $ref: '#/components/schemas/ConverterDeviceType'

    ConverterDeviceType:
      title: Тип устройства
      description: "Тип устройства: настоящее устройство или эмуляция из файла"
      type: string
      enum:
        - device
        - file
