openapi: 3.0.3
info:
  title: Модели для передачи Видео-адаптер-Матмодель кислородного конвертера
  description: 'Транспортные модели для передачи данных от Видео-адаптера до Матмодели кислородного конвертера'
  contact:
    email: okatov@datana.ru
  license:
    name: Proprietar
  version: 0.0.1
externalDocs:
  description: Дополнительная информация
  url: https://conf.dds.lanit.ru/pages/viewpage.action?pageId=48956438
#servers:
#- url: http://localhost

paths:
  /tmp:
    get:
      responses:
        200:
          description: tmp
          content: {}

components:

  schemas:

    ConverterTransportViMl:
      description: Транспортная модель для передачи данных от видео-адаптера к матмодели для кислородного конвертера
      type: object
      properties:
        frameId:
          title: Идентификатор кадра
          description: Уникальный идентификатор кадра. Строится из номера плавки, времени старта и номера кадра
          type: string
        frameTime:
          title: Время кадра
          description: Время кадра в миллисекундах от Unix-эпохи в GMT
          type: integer
          format: int64
        framePath:
          title: Адрес кадра
          description: Путь на файловой системе CEPH, по которому доступен файл видео-кадра в формате PNG
          type: string
        meltInfo:
          $ref: './spec-converter-meta.yaml#/components/schemas/ConverterMetaInfo'
