openapi: 3.0.3
info:
  title: Модели для передачи Видео-адаптер-Матмодель кислородного конвертера
  description: 'Транспортные модели для передачи данных от Видео-адаптера до Матмодели кислородного конвертера'
  contact:
    email: okatov@datana.ru
  license:
    name: Proprietar
  version: 0.0.1
externalDocs:
  description: Дополнительная информация
  url: https://conf.dds.lanit.ru/pages/viewpage.action?pageId=48956438
#servers:
#- url: http://localhost

paths:
  /tmp:
    get:
      responses:
        200:
          description: tmp
          content: {}

components:

  schemas:

    ConverterTransportAngle:
      description: Транспортная модель для передачи данных об угле наклона конвертера при сливе шлака
      type: object
      properties:
        angleTime:
          title: Время измерения угла
          description: Время в миллисекундах от Unix-эпохи в GMT, когда был получен соответствующий угол
          type: integer
          format: int64
        angle:
          title: Угол конвертера
          description: Угол в градусах, на который наклонен конвертер, определенный средствами матмодели из кадра
          type: number
          format: double
        source:
          title: Источник данных
          description: Угол в градусах, на который наклонен конвертер, определенный средствами матмодели из кадра
          type: number
          format: double
        meltInfo:
          $ref: './spec-converter-meta.yaml#/components/schemas/ConverterMeltInfo'
