openapi: 3.0.3
info:
  title: Форматы моделей для кислородного конвертера
  description: 'Транспортные модели для связи различных компонентов кислородного конвертера'
  contact:
    email: okatov@datana.ru
  license:
    name: Proprietar
  version: 0.0.1
externalDocs:
  description: Дополнительная информация
  url: https://conf.dds.lanit.ru/pages/viewpage.action?pageId=48956438
#servers:
#- url: http://localhost

paths:
  /tmp:
    get:
      responses:
        200:
          description: tmp
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConverterMeltInfo'

components:

  schemas:

    ConverterMeltInfo:
      description: Мета-информация о плавке
      type: object
      properties:
        id:
          title: Идентификатор
          description: Уникальный идентификатор плавки. Строится из даты и номера плавки
          type: string
        timeStart:
          title: Время начала
          description: Время начала плавки в миллисекундах от Unix-эпохи в GMT
          type: integer
          format: int64
        meltNumber:
          title: № плавки
          type: string
          description: Номер плавки. Не уникален
        steelGrade:
          title: марка стали
          description: Марка выплавляемой стали
          type: string
        crewNumber:
          title: № бригады
          type: string
          description: Номер бригады, выполняющей плавку
        shiftNumber:
          title: № смены
          type: string
          description: Номер смены, в которую выполняется плавка
        mode:
          title: Режим прогона
          type: string
          description: "Режим, в котором прогоняется текущая плавка: боевая, эмуляция, тестовая"
          enum:
            - prod
            - emulation
            - test
        devices:
          $ref: '#/components/schemas/ConverterMeltDevices'

    ConverterMeltDevices:
      title: Оборудование
      description: Данные об оборудовании, которое используется для мониторинга на данном агрегате
      type: object
      properties:
        converter:
          $ref: '#/components/schemas/ConverterDevicesConverter'
        irCamera:
          $ref: '#/components/schemas/ConverterDevicesIrCamerta'
        selsyn:
          $ref: '#/components/schemas/ConverterDevicesSelsyn'
        slagRate:
          $ref: '#/components/schemas/ConverterDevicesSlagRate'

    ConverterDevicesConverter:
      allOf:
        - $ref: '#/components/schemas/ConverterDevice'

    ConverterDevicesIrCamerta:
      allOf:
        - $ref: '#/components/schemas/ConverterDevice'

    ConverterDevicesSelsyn:
      allOf:
        - $ref: '#/components/schemas/ConverterDevice'

    ConverterDevicesSlagRate:
      allOf:
        - $ref: '#/components/schemas/ConverterDevice'

    ConverterDevice:
      title: Прибор
      description: Прибор - источник данных о процессах и параметрах конвертера
      type: object
      properties:
        id:
          title: Идентификтор прибора
          description: Уникальный идентификатор прибора, с которого производится съем данных
          example: converter123-irCamera1
          type: string
        name:
          title: Название
          description: Название прибора
          example: "Камера на Конвертере-2"
          type: string
        uri:
          title: Адрес устройства
          description: Адрес файла или устройства, с которого снимать изображение
          type: string
          example: "case-case1/video.ravi"
        deviceType:
          title: Тип устройства
          description: Техническое поле для десериализации. Указывает тип устройства
          type: string
        type:
          $ref: '#/components/schemas/ConverterDeviceType'
      discriminator:
        propertyName: deviceType

    ConverterDeviceType:
      title: Тип устройства
      description: "Тип устройства: настоящее устройство или эмуляция из файла"
      type: string
      enum:
        - device
        - file
        - computation

    ConverterSlagRateStub:
      title: Эмуляция по доле шлака в сливе
      description: Структура описывает процесс изменения доли шлака и стали при сливе шлака из конвертера
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ConverterSlagRateSnapshot'

    ConverterSlagRateSnapshot:
      type: object
      description: Один временной срез для эмуляции данных по доле шлака в сливе из конвертера
      properties:
        timeShift:
          title: Время
          description: Смещение по времени текущего среза относительно начала слива в милисекундах
          type: integer
          format: int64
        rateSlag:
          title: Доля шлака
          description: Доля шлака в безразмерных единицах в момент времени timeShift
          type: number
          format: double
        rateSteel:
          title: Доля стали
          description: Доля стали в безразмерных единицах в момент времени timeShift
          type: number
          format: double

    ConverterAnglesStub:
      title: Эмуляция по углам
      description: Структура описывает процесс изменения углов наклонения конвертера при сливе шлака
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ConverterAngleSnapshot'

    ConverterAngleSnapshot:
      type: object
      description: Один временной срез для эмуляции данных по углу наклона конвертера при сливе шлака
      properties:
        timeShift:
          title: Время
          description: Смещение по времени текущего среза относительно начала слива в милисекундах
          type: integer
          format: int64
        angle:
          title: Угол
          description: Угол наклонения конвертера в градусах в момент времени timeShift
          type: number
          format: double
